export const economicTheories: string[] = [
    "Supply and Demand (Invisible Hand)",
    "Classical Economics",
    "Keynesian Economics",
    "Neoclassical Synthesis (Keynesian for near-term macro; Classical for micro and long-term macro)",
    "Neo-Malthusian (Resource Scarcity)",
    "Marxism",
    "Laissez Faire Capitalism",
    "Market Socialism",
    "Monetarism",
    "Solow Model (growth comes from capital, labor, and technology)",
    "New Growth Theory (Romer & endogenous growth)",
    "Institutions and Growth (rule of law, property rights, etc.)",
    "Efficient Markets Hypothesis",
    "Permanent Income / Life Cycle Hypothesis",
    "Rational Expectations",
    "Rational Choice Theory",
    "Something Behavioral (e.g., Prospect Theory)",
    "Adverse Selection and the Lemons Problem",
    "Moral Hazard",
    "Tragedy of the Commons",
    "Property Rights as a solution to the Tragedy of the Commons",
    "Game Theory (e.g., Prisoner’s Dilemma)",
    "Comparative Advantage",
    "New Trade Theory",
    "The Trilemma (exchange rates, capital flows, and monetary policy)",
    "Washington Consensus",
    "Financial Accelerator",
    "Theory of Independent Central Banks",
    "Bagehot Theory of Central Bank Lending",
    "Creative Destruction (Schumpeter)",
    "Ricardian Equivalence",
    "Dynamic Consistency",
    "Diversification and Investment Portfolio Design",
    "Capital Asset Pricing Model",
    "Option Valuation (Black-Scholes et al.)",
    "Austrian Economics",
    "Speculative Bubbles (e.g., Minsky)",
    "Liquidationist View of Downturns",
    "Time Value of Money (incredibly important but very old)",
    "Public Choice / Economic Theory of Regulation (politicians and government workers as self-interested maximizers)",
    "Arrow’s Impossibility Theorem",
    "Welfare Theorems",
    "Veblen and Conspicuous Consumption",
    "Polluter Pays Principle (e.g., Piouvian Taxes)",
    "Offsetting Behavior (e.g., people drive safe cars more aggressively)",
    "Heckscher-Ohlin Trade Theory",
    "Optimal currency areas",
    "Exchange Rates and Purchasing Power Parity",
    "Mercantilism",
    "Rubinomics",
    "Supply-side Economics",
    "Laffer Curve",
    "Phillips Curve",
    "Theories of Economic Geography",
    "Fisher Theory of Interest Rates",
    "Liquidity Traps",
    "Resource Curse (Dutch Disease)",
    "Exchange Rate Overshooting (Dornbusch)",
    "Auctions",
    "Mechanism Design",
    "Principal-Agent Theory (e.g., separation of management and ownership)",
    "Theory of Optimal Taxation (e.g., broad base, low rate, tax less-elastic activities)"
];
